
services:

  backend:
    build: ./backend
    container_name: ft_backend
    pull_policy: if_not_present
    env_file:
      - .env
    environment:
      GAME_SERVICE_URL: http://game:8000
      SERVICE_API_KEY: super_secret_internal_key
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
      game:
        condition: service_started
    restart: on-failure
    networks:
      - ft_transcendence

  game:
    build: ./game
    container_name: ft_game
    pull_policy: if_not_present
    env_file:
      - .env
    environment:
      SERVICE_API_KEY: super_secret_internal_key
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - ft_transcendence

  db:
    image: postgres:14
    container_name: ft_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - ft_transcendence
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  frontend:
    build: ./frontend
    container_name: ft_frontend
    pull_policy: if_not_present
    ports:
      - "5173:5173"
    networks:
      - ft_transcendence

volumes:
  db_data:

networks:
  ft_transcendence:
    driver: bridge
