
services:

  frontend:
    build: ../frontend
    image: frontend:1337
    container_name: ft_frontend
    pull_policy: if_not_present
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_WS_BASE_URL: ${VITE_WS_BASE_URL}
    networks:
      - ft_transcendence

  backend:
    build: ../backend
    image: backend:1337
    container_name: ft_backend
    pull_policy: if_not_present
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      CORS_ORIGIN: ${CORS_ORIGIN}
      API_BASE_URL: ${API_BASE_URL}
      ASSET_BASE_URL: ${ASSET_BASE_URL}
      DATABASE_URL: ${DATABASE_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_EXPIRY: ${JWT_ACCESS_EXPIRY}
      JWT_REFRESH_EXPIRY: ${JWT_REFRESH_EXPIRY}
      OAUTH_42_CLIENT_ID: ${OAUTH_42_CLIENT_ID}
      OAUTH_42_CLIENT_SECRET: ${OAUTH_42_CLIENT_SECRET}
      OAUTH_42_CALLBACK_URL: ${OAUTH_42_CALLBACK_URL}
      GAME_SERVICE_URL: ${GAME_SERVICE_URL}
      SERVICE_API_KEY: ${SERVICE_API_KEY}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
      game:
        condition: service_started
    restart: on-failure
    networks:
      - ft_transcendence

  game:
    build: ../game
    image: game:1337
    container_name: ft_game
    pull_policy: if_not_present
    environment:
      SERVICE_API_KEY: ${SERVICE_API_KEY}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
    restart: on-failure
    networks:
      - ft_transcendence

  db:
    image: postgres:14
    container_name: ft_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - ft_transcendence
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  caddy:
    image: caddy:2
    container_name: ft_caddy
    pull_policy: if_not_present
    environment:
      CADDY_HOST: ${CADDY_HOST}
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - ft_transcendence

volumes:
  db_data:
    name: db_data
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config

networks:
  ft_transcendence:
    name: tic-tac-toe
    driver: bridge
