services:

  frontend:
    build: ../frontend
    image: frontend:1337
    container_name: ft_frontend
    pull_policy: if_not_present
    env_file:
      - ../.env
    networks:
      - ft_transcendence

  backend:
    build: ../backend
    image: backend:1337
    container_name: ft_backend
    pull_policy: if_not_present
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
      game:
        condition: service_started
    restart: on-failure
    volumes:
      - ./uploads:/app/uploads
    networks:
      - ft_transcendence

  game:
    build: ../game
    image: game:1337
    container_name: ft_game
    pull_policy: if_not_present
    env_file:
      - ../.env
    networks:
      - ft_transcendence

  db:
    image: postgres:14
    container_name: ft_postgres
    restart: always
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ft_transcendence

  caddy:
    image: caddy:2
    container_name: ft_caddy
    pull_policy: if_not_present
    env_file:
      - ../.env
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ft_transcendence

volumes:
  db_data:
    name: db_data
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config

networks:
  ft_transcendence:
    name: tic-tac-toe
    driver: bridge
